apiVersion: apps/v1
kind: Deployment
metadata:
  name: cesco-ai-helpdesk
  namespace: cesco-poc-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cesco-ai-helpdesk
  template:
    metadata:
      labels:
        app: cesco-ai-helpdesk
        version: v1
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: cesco-ai-helpdesk
        image: chanran33/cesco-ai-helpdesk:0.0.6
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 745Mi
        ports:
          - containerPort: 8501
        
---
apiVersion: v1
kind: Service
metadata:
  name: cesco-ai-helpdesk-service
  namespace: cesco-poc-1
spec:
  selector:
    app: cesco-ai-helpdesk
  type: NodePort #LoadBalancer #ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: cesco-ai-helpdesk-api-rule
  namespace: cesco-poc-1
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: cesco-ai-helpdesk-api-rule.api.c-440ed3d.kyma.ondemand.com
  service:
    name: cesco-ai-helpdesk-service
    port: 8501
  rules:
    - path: /.*
      methods: ["GET", "POST"]
      mutators: []
      accessStrategies:
        - handler: allow
          config: {}